# Dependencies
markdown:         kramdown

# Setup
title:            Fred Cook
tagline:          'Personal Website'
description:      'Programmer'
url:              https://fred-cook.github.io/
baseurl:          /

author:
  name:           'Fred Cook'

paginate:         5
paginate_path: "/_posts:num/"


# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/fred-cook/website