# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Fred Cook
tagline:          'Personal Website'
description:      'Programmer'
url:              https://fred-cook.github.io/website/
baseurl:          /

author:
  name:           'Fred Cook'

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/fred-cook/website